title: Uasoni
description:
baseurl: ""
url: https://uasoni.github.io

# Site Settings
author:
  name: Austin Song
  email: n/a
photo: /assets/images/profile.jpg

# Social Media
social:
  github: uasoni

# Build Settings
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml

posts:
  enabled: true
  permalink: /:title:output_ext

kramdown:
  parse_span_html: false

# Collections
# collections:
#   posts:
#     output: true
#     permalink: /:collection/:title:output_ext
#   projects:
#     output: true
#     permalink: /:collection/:title:output_ext

# Plugins
# plugins:
#   - jekyll-seo-tag